"""Add visualizations table

Revision ID: 0d23f9a573c3
Revises: 5b8e073847a6
Create Date: 2025-06-11 12:41:36.711783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d23f9a573c3'
down_revision = '5b8e073847a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 